/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mainpackage;

import java.sql.*;
import java.sql.Connection;
import javax.swing.JOptionPane;
/**
 *
 * @author Admin
 */
public class Register extends javax.swing.JFrame {

    //Database Connection Variables
    static final String db_url = "jdbc:mysql://localhost:3306/retail_db";
    static final String username = "root";
    static final String password = "";
    
    public Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Header = new javax.swing.JLabel();
        EmailAddress = new javax.swing.JTextField();
        Username = new javax.swing.JTextField();
        passWord = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        submitButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        bgImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backgroundPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Brand Logo -  (400).png"))); // NOI18N
        backgroundPanel.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, 350));

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("and financial ally");
        backgroundPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 360, 60));

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Here to be your trusted business");
        backgroundPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 350, 60));

        Header.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        Header.setForeground(new java.awt.Color(51, 204, 255));
        Header.setText("Admin Register");
        backgroundPanel.add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 40, -1, -1));

        EmailAddress.setBackground(new java.awt.Color(18, 18, 18));
        EmailAddress.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        EmailAddress.setForeground(new java.awt.Color(255, 255, 255));
        EmailAddress.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));
        backgroundPanel.add(EmailAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 310, 380, 40));

        Username.setBackground(new java.awt.Color(18, 18, 18));
        Username.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Username.setForeground(new java.awt.Color(51, 204, 255));
        Username.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 1, true));
        backgroundPanel.add(Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 210, 380, 40));

        passWord.setBackground(new java.awt.Color(18, 18, 18));
        passWord.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        passWord.setForeground(new java.awt.Color(255, 255, 255));
        passWord.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));
        backgroundPanel.add(passWord, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 410, 380, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 204, 255));
        jLabel3.setText("Username");
        backgroundPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 204, 255));
        jLabel4.setText("Email Address");
        backgroundPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 280, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 204, 255));
        jLabel5.setText("Password");
        backgroundPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 380, -1, -1));

        submitButton.setBackground(new java.awt.Color(0, 204, 204));
        submitButton.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        submitButton.setForeground(new java.awt.Color(0, 0, 0));
        submitButton.setText("Register");
        submitButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        backgroundPanel.add(submitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 480, 190, 50));

        jLabel6.setForeground(new java.awt.Color(51, 204, 255));
        jLabel6.setText("Log In");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        backgroundPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 596, -1, 20));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Already have an Account?");
        backgroundPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(617, 596, 140, 20));

        bgImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/Register.png"))); // NOI18N
        backgroundPanel.add(bgImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(backgroundPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 630));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
       Login log = new Login();
       log.setVisible(true);
       setVisible(false);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        String userN, emailAd, passW;
        
        try {
            Connection conn = DriverManager.getConnection(db_url, username, password);
            Statement stmt = conn.createStatement();
            if ("".equals(Username.getText())) {
                JOptionPane.showMessageDialog(this, "Full Name is Required");
            }else if("".equals(EmailAddress.getText())){
                JOptionPane.showMessageDialog(this, "Email Address is Required");
            }else if("".equals(passWord.getText())){
                JOptionPane.showMessageDialog(this, "Password is Required");
            }
            else{
                    String userInput = Username.getText().trim();
                    String emailInput = EmailAddress.getText().trim();
                    String passcode = passWord.getText().trim();
                    
                    String insertQuery = "INSERT INTO admin_accounts (username,email_address,password) VALUES ('" + userInput + "', '" + emailInput + "', '" + passcode + "')";
                    
                    stmt.executeUpdate(insertQuery);
                    
                    Username.setText("");
                    EmailAddress.setText("");
                    passWord.setText("");
                    JOptionPane.showMessageDialog(this, "New Admin Account Created Successfully!");
                    
                    Login log = new Login();
                    log.setVisible(true);
                    setVisible(false);
                    
            }
        } catch (SQLException e) {
            System.out.println("Error" + e.getMessage());
        }
    }//GEN-LAST:event_submitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EmailAddress;
    private javax.swing.JLabel Header;
    private javax.swing.JTextField Username;
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JLabel bgImage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel logo;
    private javax.swing.JPasswordField passWord;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
