/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mainpackage;

import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Admin
 */
public class SplashScreen extends javax.swing.JFrame {

    /**
     * Creates new form SplashScreen
     */
    public SplashScreen() {
        initComponents();
        
        loadingBar.setUI(new javax.swing.plaf.basic.BasicProgressBarUI() {
            protected Color getSelectionBackground() { return Color.BLACK; }
            protected Color getSelectionForeground() { return Color.BLACK; }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        background = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        loadingBar = new javax.swing.JProgressBar();
        modules = new javax.swing.JLabel();
        percent = new javax.swing.JLabel();
        bgLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(940, 631));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Brand Logo - 500px.png"))); // NOI18N
        background.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 380));

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 204, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Retail Sales Transaction Management System");
        background.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 720, 130));

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("1.0.0 BETA 1");
        background.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 460, 260, 50));

        jSeparator1.setForeground(new java.awt.Color(0, 255, 255));
        background.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 450, 740, 40));

        loadingBar.setBackground(new java.awt.Color(0, 102, 102));
        loadingBar.setForeground(new java.awt.Color(51, 204, 255));
        loadingBar.setBorder(null);
        loadingBar.setStringPainted(true);
        background.add(loadingBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 550, 470, 20));

        modules.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        modules.setForeground(new java.awt.Color(0, 255, 255));
        modules.setText("Starting");
        background.add(modules, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 520, -1, -1));

        percent.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        percent.setForeground(new java.awt.Color(0, 255, 255));
        percent.setText("0%");
        background.add(percent, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 520, 30, -1));

        bgLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/Splash Screen.png"))); // NOI18N
        background.add(bgLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 630));

        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 640));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
         try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()){
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException e) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, e);
        }
        
        SplashScreen sp = new SplashScreen();
        sp.setVisible(true);
        
        try {
                
                for (int i = 0; i <= 100; i++) {
                    Thread.sleep(100);
                    sp.percent.setText(i + "%");
                    
                    if (i == 10) {
                        sp.modules.setText("Loading Modules...");
                    }
                    if (i == 20) {
                        sp.modules.setText("Connecting to Database...");
                    }
                    if (i == 50) {
                        sp.modules.setText("Fetching Data...");
                    }
                    if (i == 70) {
                        sp.modules.setText("Unpacking Resources...");
                    }
                    if (i == 80) {
                        sp.modules.setText("Activating Packages and Frames...");
                    }
                    if (i == 100) {
                        sp.modules.setText("Launching Successful...");
                        
                        sp.setVisible(false);
                        Main home = new Main();
                        home.setVisible(true);
                    }
                    sp.loadingBar.setValue(i);
                    
                    
                    
                    
                    
                }
        } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);        
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JLabel bgLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JProgressBar loadingBar;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel modules;
    private javax.swing.JLabel percent;
    // End of variables declaration//GEN-END:variables
}
